// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenFiles(arg1) {
  return window['go']['main']['App']['GenFiles'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDir() {
  return window['go']['main']['App']['OpenDir']();
}
